### PR TITLE
Add support for more consul params.

### PR DESCRIPTION
**Pull request by rantav**
dc - to select a DC
allow-stale - to allow stale data at the agent
require-consistent - to require consistency from the agent

### CODE REVIEW

**Comment by rantav** [comment]
Cool, can you also please add a tag @mbobakov ?

**Comment by mbobakov** [comment]
Done

**Comment by rantav** [comment]
I am sorry @mbobakov but go mod requires that the tag start with `v` so the correct tag needs to be `v1.3.0` (and not `1.3.0`)
thanks...

**Comment by mbobakov** [comment]
Done

**Pull request merged**
